using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

public class FOW_Enemy : MonoBehaviour
{
    [Header("===Tweaking them Please!!!!==============================================================================================")]
    public float ViewRadius;
    [Range(0, 360)]
    public float ViewAngle;
    public int MeshResolution;

    [Header("Assign Values==============================================================================================")]
    [SerializeField] LayerMask _obstacles;
    [SerializeField] LayerMask _target;
    public List<Transform> VisibleObjects=new List<Transform> ();
    [SerializeField] GameObject _spotImage;
    [SerializeField] PlayerManager _p_M;
    public MeshFilter FOW_Filter;
    Mesh _viewMesh;



    private void Start()
    {
        _viewMesh=new Mesh ();
        FOW_Filter.mesh = _viewMesh;
        StartCoroutine("LineOfSight", 0.2f);
        _p_M.LoseLevel = false;
        //if (_spotImage != null)
        //{
        //    _spotImage.SetActive(false);
        //     _p_M.LoseLevel = false;
        //}
    }
    private void Update()
    {
        //if (_p_M.LoseLevel && Input.GetKeyDown(KeyCode.Space))
        //{
        //    SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
        //}
        //only use this for testing Delete afterwards 
    }
    private void LateUpdate()
    {
        DrawFieldOfView();
    }
    
    IEnumerator LineOfSight(float Delay)
    {
        while (true)
        {
            yield return new WaitForSeconds(Delay);
            DetectPlayer();
        }
    }
    public Vector3 AngleDir(float angleDegree,bool IsGlobalAngle)
    {
        if (!IsGlobalAngle)
        {
            angleDegree += transform.eulerAngles.y;
        }
        return new Vector3(Mathf.Sin(angleDegree * Mathf.Deg2Rad), 0, Mathf.Cos(angleDegree * Mathf.Deg2Rad));
    }

    public void DetectPlayer()
    {
        VisibleObjects.Clear ();
        Collider[] InTheRangeObjects=Physics.OverlapSphere(transform.position,ViewRadius,_target);
        for(int i = 0; i < InTheRangeObjects.Length; i++)
        {
            Transform target= InTheRangeObjects[i].transform;
            Vector3 targetDir=(target.transform.position-transform.position).normalized;//GEt direction of that 
            float betweenAngle=Vector3.Angle(transform.forward, targetDir);//check if the target is inside the Line of sight angle
            if(betweenAngle < (ViewAngle/2))
            {
                float dis = Vector3.Distance(target.transform.position, transform.position);
                if (!Physics.Raycast(transform.position, targetDir, dis, _obstacles))//if there is no obstacles inbetween target and object with vision
                {
                    VisibleObjects.Add(target); //It means the target has been seen
                                                //if (_spotImage != null)
                                                //{
                                                //    _spotImage.SetActive(true);
                                                //     _p_M.LoseLevel = true;
                                                //}
                    _p_M.LoseLevel = true;
                }
            }
        }
    }

    public void DrawFieldOfView()
    {
        int stepCount = Mathf.RoundToInt(ViewAngle * MeshResolution);
        float stepAngle=ViewAngle/stepCount;
        List<Vector3> hitPoints=new List<Vector3>();    
        for(int i = 0;i < stepCount-1; i++)
        {
            float angle = transform.eulerAngles.y - ViewAngle / 2 + stepAngle * i;
           // Debug.DrawLine(transform.position, transform.position + AngleDir(angle, true) * ViewRadius, Color.red);
           ViewCastInfo newViewCast=ViewCast(angle);
            hitPoints.Add(newViewCast.HitPoint);
        }
        //remember the vectors here are all local
        int verticesCount=hitPoints.Count+1;
        int triangleNum = verticesCount - 2;
        Vector3[] vertices=new Vector3[verticesCount];  
        int[] trangle_Vertices=new int[(triangleNum) *3];//this is how many combination of vertices are for all triangles

        vertices[0] = Vector3.zero;
        for(int i = 0; i < verticesCount-1; i++)
        {
            vertices[i + 1] = transform.InverseTransformPoint(hitPoints[i]);
            if(i < triangleNum)
            {
                trangle_Vertices[i * 3] = 0;
                trangle_Vertices[i * 3 + 1] = i + 1;
                trangle_Vertices[i * 3 + 2] = i + 2;
            }
        }

        _viewMesh.Clear();
        _viewMesh.vertices = vertices;
        _viewMesh.triangles = trangle_Vertices;
        _viewMesh.RecalculateNormals();

    }

    ViewCastInfo ViewCast(float globalAngle)
    {
        Vector3 dir = AngleDir(globalAngle, true);
        RaycastHit hit;
        if(Physics.Raycast(transform.position,dir,out hit, ViewRadius, _obstacles))
        {
            return new ViewCastInfo(true,hit.point,globalAngle,hit.distance);//remember to use new sturt to rewrite the value. 
        }
        else
        {
            return new ViewCastInfo(false, transform.position+dir*ViewRadius, globalAngle, ViewRadius);
        }
    }

    public struct ViewCastInfo//all the variables inside cannot be called outside this struct or ths function 
    {
        public bool Hit;
        public Vector3 HitPoint;
        public float Angle;
        public float Distance;

        public ViewCastInfo(bool _hit,Vector3 _hitPoint,float _angle,float _distance)
        {
            Hit = _hit;
            HitPoint = _hitPoint;
            Angle = _angle;
            Distance = _distance;
        }
    }

}
